title: Paulo Souza Junior
description: Ph.D. Student and Early Stage Researcher participating in the EU project named FogGuru. Currently working with Application resource management techniques over Fog environments.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: Paulo Souza Junior
tagline: Ph.D. Student at Université de Rennes 1
about-description: Ph.D. Student and Early Stage Researcher participating in the <a href="http://fogguru.eu">FogGuru</a> project. 
                   Currently working with Application resource management techniques over Fog environments. # Add Discription
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: parodrig@irisa.fr # Add your Email address
website: paulosouzajr.github.io # Add your website, do not add http://
linkedin: paulo-souza-junior #Add your Linkedin handle
github: paulosouzajr # Add your Github handle
twitter: '@paulorrsj' # Add your Twitter handle
instagram: prrsoujr

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets

exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
